db_file: './Crosswalk_Database.json'
preprocess_width: 300
preprocess_height: 240
exifmeta: {'ImageWidth', 'ImageLength', 'Make', 'Model', 'GPSInfo',         'DateTimeOriginal', 'BrightnessValue'}
manualmeta: { # [min, max, initial]
              'obs_car': [0, 1, 0],
              'obs_human': [0, 1, 0],
              'shadow': [0, 1, 0],
              'column': [1, 2, 1],
              'zebra_ratio': [0, 100, 0],
              'out_of_range' : [0, 1, 0],
              'old' : [0, 1, 0]
             }