db_file: './Crosswalk_Database.json'
npy_log_file: './makenp_log.txt'
data_dir: ./preprocessed_data/
preprocess_width: 150
preprocess_height: 120
exifmeta: {'ImageWidth', 'ImageLength', 'Make', 'Model', 'GPSInfo', 'DateTimeOriginal', 'BrightnessValue'}
manualmeta: { # [min, max, initial]
              'obs_car': [0, 1, 0],
              'obs_human': [0, 1, 0],
              'shadow': [0, 1, 0],
              'column': [1, 2, 1],
              'zebra_ratio': [0, 100, 60],
              'out_of_range' : [0, 1, 0],
              'old' : [0, 1, 0],
              'invalid' : [0, 0, 0]
             }
experiment_name: 'Crosswalk_guide_150_120'
train_imgs: './npy/2019-04-02__08-01-41_X.npy'
train_labels: './npy/2019-04-02__08-01-41_Y.npy'
val_imgs: './npy/2019-04-02__07-57-59_X.npy'
val_labels: './npy/2019-04-02__07-57-59_Y.npy'
num_gpus: 1
network: 'SimpleModel'
width: 150
height: 120
epochs: 30
batch_size: 8
learning_rate: 0.001
sgd_momentum: .9
step_decay: False
drop_factor: .5
epochs_until_drop: 10
optimizer: 'SGD'
batch_momentum: .9 
weight_decay: 0.0001
augmentation: False
affine_augs: False