npy_log_file: './makenp_log.txt'
data_dir: ./preprocessed_data/
x_train: './npy/200205_60_80/train_x.npy'
y_train: './npy/200205_60_80/train_y.npy'
x_val: './npy/200205_60_80/val_x.npy'
y_val: './npy/200205_60_80/val_y.npy'
#x_val: './npy/200204_3_labels/val_x.npy'
#y_val: './npy/200204_3_labels/val_y.npy'
num_gpus: 1
network: 'MobileNetV2s'
width: 60
height: 79
grayscale: False
epochs: 100
batch_size: 64
learning_rate: 0.0002
sgd_momentum: .9
step_decay: True
drop_factor: .5
epochs_until_drop: 15
optimizer: 'Adam'
batch_momentum: .9 
weight_decay: 0.0001
augmentation: False
affine_augs: False
