npy_log_file: './makenp_log.txt'
data_dir: ./preprocessed_data/
x_train: './npy/2020-01-23_good_eval_train_x.npy'
y_train: './npy/2020-01-23_good_eval_train_y.npy'
x_val: './npy/2020-01-23_good_eval_val_x.npy'
y_val: './npy/2020-01-23_good_eval_val_y.npy'
num_gpus: 1
network: 'Simplified'
width: 150
height: 199
grayscale: False
epochs: 20
batch_size: 32
learning_rate: 0.00002
sgd_momentum: .9
step_decay: True
drop_factor: .5
epochs_until_drop: 20
optimizer: 'Adam'
batch_momentum: .9 
weight_decay: 0.0001
augmentation: False
affine_augs: False
