experiment_name: 'Crosswalk_guide'
train_imgs: './preprocessed_data/train/X.npy'
train_labels: './preprocessed_data/train/Y.npy'
val_imgs: './preprocessed_data/test/X.npy'
val_labels: './preprocessed_data/test/Y.npy'
num_gpus: 1
network: 'SimpleModel'
height: 240
width: 300
epochs: 70
batch_size: 4
learning_rate: 0.001
sgd_momentum: .9
step_decay: False
drop_factor: .5
epochs_until_drop: 10
optimizer: 'SGD'
batch_momentum: .9 
weight_decay: 0.0001
augmentation: True
affine_augs: True

