npy_log_file: './makenp_log.txt'
data_dir: ./preprocessed_data/
experiment_name: 'Crosswalk_guide_150_120'
val_imgs: './npy/2019-06-21__07-35-44_X.npy'
val_labels: './npy/2019-06-21__07-35-44_Y.npy'
num_gpus: 1
network: 'SimpleModel'
width: 400
height: 400
epochs: 30
batch_size: 8
learning_rate: 0.001
sgd_momentum: .9
step_decay: False
drop_factor: .5
epochs_until_drop: 10
optimizer: 'SGD'
batch_momentum: .9 
weight_decay: 0.0001
augmentation: False
affine_augs: False