npy_log_file: './makenp_log.txt'
data_dir: ./preprocessed_data/
experiment_name: '2019-sep21-5k'
x_train: './npy/x_train_190921.npy'
y_train: './npy/y_train_190921.npy'
x_val: './npy/x_val_190921.npy'
y_val: './npy/y_val_190921.npy'
num_gpus: 1
network: 'MobileNetV2'
width: 150
height: 199
grayscale: False
epochs: 100
batch_size: 16
learning_rate: 0.0001
sgd_momentum: .9
step_decay: True
drop_factor: .5
epochs_until_drop: 10
optimizer: 'Adam'
batch_momentum: .9 
weight_decay: 0.0001
augmentation: False
affine_augs: False
